name: CI | Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - name: Build lottie-to-apng
        run: docker build -t lottie-to-apng:${{ matrix.platform }} --target lottie-to-apng --platform ${{ matrix.platform }} .

      - name: Upload lottie-to-apng as artifact
        uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with:
          image: lottie-to-apng:${{ matrix.platform }}

      - name: Build lottie-to-gif
        run: docker build -t lottie-to-gif:${{ matrix.platform }} --target lottie-to-gif --platform ${{ matrix.platform }} .

      - name: Upload lottie-to-gif as artifact
        uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with:
          image: lottie-to-gif:${{ matrix.platform }}

      - name: Build lottie-to-png
        run: docker build -t lottie-to-png:${{ matrix.platform }} --target lottie-to-png --platform ${{ matrix.platform }} .

      - name: Upload lottie-to-png as artifact
        uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with:
          image: lottie-to-png:${{ matrix.platform }}

      - name: Build lottie-to-webp
        run: docker build -t lottie-to-webp:${{ matrix.platform }} --target lottie-to-webp --platform ${{ matrix.platform }} .

      - name: Upload lottie-to-webp as artifact
        uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with:
          image: lottie-to-webp:${{ matrix.platform }}

  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - lottie-to-apng
          - lottie-to-gif
          - lottie-to-png
          - lottie-to-webp
        platform:
          - amd64
          - arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Download ${{ matrix.image }} image as artefact
        uses: ishworkh/docker-image-artifact-download@v2.0.1
        with:
          image: ${{ matrix.image }}:${{ matrix.platform }}

      - uses: actions/checkout@v3

      - name: Run ${{ matrix.image }} tests
        run: docker run --rm -v $(pwd)/test-files:/source --platform ${{ matrix.platform }} ${{ matrix.image }}:${{ matrix.platform }}
