name: Converting Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build lottie-to-apng
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-apng
          tags: lottie-to-apng
          load: true

      - name: Run lottie-to-apng conversion
        run: docker run --rm -v $(pwd)/test-files:/source lottie-to-apng

      - name: Build lottie-to-gif
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-gif
          tags: lottie-to-gif
          load: true

      - name: Run lottie-to-gif conversion
        run: docker run --rm -v $(pwd)/test-files:/source lottie-to-gif

      - name: Build lottie-to-png
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-png
          tags: lottie-to-png
          load: true

      - name: Run lottie-to-png conversion
        run: docker run --rm -v $(pwd)/test-files:/source lottie-to-png

      - name: Build lottie-to-webp
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-webp
          tags: lottie-to-webp
          load: true

      - name: Run lottie-to-webp conversion
        run: docker run --rm -v $(pwd)/test-files:/source lottie-to-webp

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push lottie-to-apng
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-apng
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lottie-to-apng:latest
          push: true

      - name: Push lottie-to-gif
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-gif
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lottie-to-gif:latest
          push: true

      - name: Push lottie-to-png
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-png
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lottie-to-png:latest
          push: true

      - name: Push lottie-to-webp
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          target: lottie-to-webp
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lottie-to-webp:latest
          push: true
